title = "this is the title"

[database]
    path = "./tmp/SE.db"  # 数据库存储路径
    type = "sqlite3"      # 数据库类型，默认 sqlite3
    sqlSchemeInit = "./tmp/Scheme.sql" # 初始化数据库的文件
    sqlSchemeCheck = "./tmp/SchemeCheck.sql" # 检查数据库完整性的文件

[log]
    path = "./tmp/SE.log" # 默认日志文件路径

[server]
    capcity = 500     # 令牌桶初始值及最大容量
    quantum = 200     # 每秒新增请求数
    key = "privatekey" # 用于生成token的密钥
    period = 2 # expire time of token
        