title = "API Reference Manual"
address = "localhost"
port = "8080"

[FrontendInterface]
    [test]
        path="/test"
        func="Test whether the server is running"
        ret=[
            "Test OK"
        ]
